### ISSUE TITLE
Missing animation name

### ISSUE THREAD

**Issue by sylvainbaronnet** [nucliweb/postcss-magic-animations-data#1]
For example : `perspectiveLeftReturn`

see : https://minimamente.com/example/magic_animations/

**Comment by nucliweb** [comment]
Hi @sylvainbaronnet thank you for warning.

I update with a last version of Magic animations.
Please update plugin to version `0.3.0` https://github.com/nucliweb/postcss-magic-animations

**Comment by sylvainbaronnet** [comment]
Awesome thanks !
